development:
  gmail:
    user_name: zombie.on.rails
    password: zor57$jp
test:
  gmail:
    user_name: zombie.on.rails
    password: zor57$jp
production:
  gmail:
    user_name: zombie.on.rails
    password: zor57$jp